#!/bin/bash

clear
rm start
if [ -s $HOME/TGS/data.json ]
then
echo -e "Welcome back $(cat $HOME/TGS/data.json | jq '.[0].name')\n How can i serve You?"
else
mkdir $HOME/TGS
clear
echo -e "Welcome to TheGuildScript-TGS-V1.0 Chosen One\
\nI must ask you some question\
\nWhat is your name? I will use this name as node name, if this will be necessary\nPls enter your name and press Enter"
read name
echo -e "$name ok, do you want install firewall UFW for better secure?\n(Yes/No)"
while read response; do
case $response in
    [yY][eE][sS]|[yY])
    echo "What port you want open?"
    while read port; do
    case $port in
    [0-9])
    ufwPort+=($port)
    echo ufwPort
    clear
    sudo netstat -tulpn
    echo -e '$port will be open\nType "(d)one" if you finish, or enter another port'
    ;;
    [dD][oO][nN][eE]|[dD])
        break
        ;;
     *)
echo "Note a number type done if you finish"
esac
done
        ufwStatus=enable
        break
        ;;
    [nN][oO]|[nN])
        ufwStatus=disable
        break
        ;;
        *)
echo "Please, enter Y(yes) or N(no)! "
esac
done
echo $name
echo '[]' | jq '. +[{"name":"'$name'","ufwStatus":"'$ufwStatus'"}]' >  $HOME/TGS/data.json
#curl https://raw.githubusercontent.com/TheGuild-ops/tool/main/init | bash

fi

echo -e " Psl choose your action; \n 1 - install node; \n 2 - upgrade node \n"
read action

case "$action" in
  1 ) echo "ToDo";;
  2 ) echo "Цифра";;
  * ) echo "Ничего не выбрано";;
esac

