#!/bin/bash
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install git curl build-essential jq -y
sudo rm -rf /usr/local/go
curl https://dl.google.com/go/go1.15.7.linux-amd64.tar.gz | sudo tar -C/usr/local -zxvf -
cat <<'EOF' >>$HOME/.profile
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export GO111MODULE=on 
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
EOF
source $HOME/.profile
go version

projectName=rizon

mkdir /root/TGS/source
mkdir /root/TGS/data
mkdir /root/TGS/data/$projectName/
mkdir /root/TGS/bin/
cd /root/TGS/source
git clone https://github.com/rizon-world/rizon.git && cd rizon
git fetch && git checkout v0.1.0
make install
echo "export NICKNAME=$(cat /root/TGS/data.json | jq ".[0].name") " >> ~/.bash_profile && source ~/.bash_profile
$HOME/go/bin/rizond init $NICKNAME --chain-id adora
wget https://raw.githubusercontent.com/rizon-world/testnet/master/genesis.json 
mv genesis.json $HOME/.rizon/config
sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.0001uatolo"/g' $HOME/.rizon/config/app.toml
sed -i 's/seeds = ""/seeds = "bad95d276696706c4df2272d45395d7da4a13f43@13.124.50.97:26656,08c0e4c197a0607a9832f9b365d07cef9b04a859@3.34.181.126:26656,34cec0c4ada4cd7f8ad26c457d604edc0eff3cb0@13.124.253.195:26656,72016f93daf677147c5d1d2625273dde61ae2d0a@3.34.5.208:26656"/g' $HOME/.rizon/config/config.toml

sudo tee <<EOF >/dev/null /etc/systemd/system/$projectName.service
[Unit]
Description=Rizon Node
After=network-online.target
[Service]
User=$USER
ExecStart=/root/TGS/bin/$projectName/ start
Restart=always
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable rizond
sudo systemctl restart rizond
sudo journalctl -u rizond -f
