#!/bin/bash
rm rizon*
ufw allow 26656
ufw allow 26657
ufw allow 26655

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install git curl build-essential jq -y
sudo rm -rf /usr/local/go
curl https://dl.google.com/go/go1.15.7.linux-amd64.tar.gz | sudo tar -C/usr/local -zxvf -
cat <<'EOF' >>$HOME/.profile
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export GO111MODULE=on 
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
EOF
source $HOME/.profile
go version

projectName=rizon

mkdir /root/TGS/source
mkdir /root/TGS/data
mkdir /root/TGS/data/$projectName/
mkdir /root/TGS/bin/
cd /root/TGS/source
git clone https://github.com/rizon-world/rizon.git && cd rizon
git fetch && git checkout v0.1.0
make install
echo "export NICKNAME=$(cat /root/TGS/data.json | jq ".[0].name")" >> ~/.bash_profile && source ~/.bash_profile
$HOME/go/bin/rizond init $NICKNAME --chain-id adora
wget https://raw.githubusercontent.com/rizon-world/testnet/master/genesis.json 
mv genesis.json $HOME/.rizon/config
sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.0001uatolo"/g' $HOME/.rizon/config/app.toml
sed -i 's/seeds = ""/seeds = "d95b51d2cf05446b59cc85d4c95758985e8f78e8@157.230.33.131:26656, 765e16083b5bd1740a759370ad9001de9af8409d@172.104.184.201:26656, b197e7a5c3a70d6e6d5d65a09d881fa4ff597201@65.21.106.221:26656, fc40d080708997112f799afaac09c667a560131a@65.21.184.214:26656"/g' $HOME/.rizon/config/config.toml

sudo tee <<EOF >/dev/null /etc/systemd/system/$projectName.service
[Unit]
Description=Rizon Node
After=network-online.target
[Service]
User=$USER
ExecStart=$HOME/go/bin/rizond start
Restart=always
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable $projectName
sudo systemctl restart $projectName
sudo journalctl -u $projectName -f
