#!/bin/bash

cd 
mkdir TGS
cd TGS
mkdir node
cd node
git clone $gitUrl
cd $projectName
git checkout $projectVersion
make install
rm .omniflixhub/config/
rm /root/.omniflixhub/config/genesis.json
echo Y | $projectFile keys add $monikerName >> /root/TGS/dataKey-$projectName.js 2>&1
$projectFile unsafe-reset-all 
$projectFile init $monikerName --chain-id $projectChainId
curl $projectGenesisUrl > ~/.$projectName/config/genesis.json

sed -i.bak -e "s/^seeds *=.*/seeds = \"$projectSeeds\"/" ~/.$projectName/config/config.toml
sed -i.bak -e "s/^moniker *=.*/moniker = $monikerName/" ~/.$projectName/config/config.toml
sed -i.bak -e "s/^pprof_laddr *=.*/pprof_laddr = \"localhost\x3A$projectRpcPort\"/" ~/.$projectName/config/config.toml
sed -i.bak -e "s/^proxy_app *=.*/proxy_app = \"tcp:\x2F\x2F127.0.0.1:$projectWsPort\"/" ~/.$projectName/config/config.toml
sed -i.bak -e "s/^laddr *=.*/laddr = \"tcp:\x2F\x2F0.0.0.0:$projectPort\"/" ~/.$projectName/config/config.toml
sed -i.bak -e "s/^address *=.*/address = \"0.0.0.0:$pPort1\"/" ~/.$projectName/config/app.toml
sed -i.bak -e "0,/^laddr *=.*/laddr = \"tcp:\x2F\x2F0.0.0.0:$projectPort\"/" ~/.$projectName/config/config.toml

echo $projectRpcPort
echo $projectWsPort
echo $projectPort

ufw allow $projectRpcPort
ufw allow $projectWsPort
ufw allow $projectPort

sudo tee /etc/systemd/system/$projectFile.service > /dev/null <<EOF
[Unit]
Description=$projectFile Daemon
After=network-online.target

[Service]
User=$USER
ExecStart=$(which omniflixhubd) start
Restart=always
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable $projectFile
sudo systemctl start $projectFile
journalctl -f -u $projectFile
