#!/bin/bash

cd 
mkdir TGS
cd TGS
mkdir node
cd node
git clone $gitUrl
cd $projectName
git checkout $projectVersion
make install

$projectFile init $monikerName --chain-id $projectChainId
curl $projectGenesisUrl > ~/.$projectName/config/genesis.json

$projectFile keys add $monikerName
projectFile unsafe-reset-all 
sed -i.bak -e "s/^seeds *=.*/seeds = \"$projectSeeds\"/; s/^persistent_peers *=.*/persistent_peers = \"$projectPeers\"/" ~/.$projectFile/config/config.toml

ufw allow $projectRpcPort
ufw allow $projectWsPort
ufw allow $projectPort

sudo tee /etc/systemd/system/$projectFile.service > /dev/null <<EOF
[Unit]
Description=$projectFile Daemon
After=network-online.target

[Service]
User=$USER
ExecStart=/bin/$projectFile start
Restart=always
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable $projectFile
sudo systemctl start $projectFile
journalctl -f -u $projectFile
